[project]
name = "aipodcast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "drissionpage>=4.1.0.18",
    "httpx>=0.28.1",
    "moviepy>=2.1.2",
    "openai>=1.78.1",
    "pandas>=2.2.3",
    "tqdm>=4.66.1",
]
